### ISSUE TITLE
DNS and DHCP would be great features

### ISSUE THREAD

**Issue by drksbr** [nickjfree/goose#2]
This would be very, very interesting if it had a DNS server and a built-in DHCP that could deliver IP addresses within a Pool and resolve names to /32 ips ips that were delivered.

Ex.:
Master:
./goose -e ipfs/xxxxxxxxx -l 192.168.100.1/24 -name NODE0
slaves:
./goose -e ipfs/xxxxxxxxx -dhcp true -name NODE1
./goose -e ipfs/xxxxxxxxx -dhcp true -name NODE2
./goose -e ipfs/xxxxxxxxx -dhcp true -name NODE3

ping node1
ping 192.168.100.2

ping node2
ping 192.168.100.3

...

That would be epic.

**Comment by nickjfree** [comment]
Thank you for your suggestion! Adding a DNS server and built-in DHCP to would be a great idea!

**Comment by drksbr** [comment]
I'm just getting started in the Go language, but I'm going to download the repository on my machine and try to develop something related to it. I don't know much about it but I'm learning.
