### ISSUE TITLE
Does Goose use QUIC?

### ISSUE THREAD

**Issue by lonnietc** [nickjfree/goose#6]
Hello, 

It seems that Goose routers could be very useful for massive scaling P2P project that I am researching at the moment.

I am wondering 2 things.

1. Does Goose use QUIC as I understand that it is much faster than TCP and more akin to reliable UDP which would make it faster, I think.

2. I am wondering how well it would scale for speed and even though the Water TAP/TUN interface seems very good, I was wondering if you had considered using Wireguard which is also available cross-platform as well?

It seems like it could be more of a Virtual Router which could be good, but in reading the real-world scenario, connecting multiple nodes that may already be on the same masqueraded IP network might run into IP conflicts, if I read your scenario correctly.

Could you please clarify this for me?

also, in reading over the other submitted issues, I absolutely agree that built-in DNS and DHCP would be very benefitable, indeed.

Thanks in advance.

**Comment by nickjfree** [comment]
Hi @lonnietc,

Thanks for your curiosity about Goose!

You're right. Goose does indeed use QUIC. Goose uses libp2p, a modular network stack  for building P2P applications. One of the standout features of libp2p is its support for various transport protocols, with QUIC being the default. This is why Goose uses QUIC. Moreover, I've chosen to utilize the unreliable datagrams feature of QUIC, a part of the protocol itself. The standard QUIC is stream-based and incorporates a retransmission logic which can sometimes create slowdowns. In contrast, unreliable datagrams bypass this retransmission logic, which makes them more similar to UDP and better suited for building tunnels, a key aspect of Goose's functionality.

As of now, Goose uses the Water TAP/TUN interface. This choice is straightforward and compatible across many platforms. Wireguard is a strong technology, but folding it into Goose would mean a substantial reworking of the code. Given that Goose began as an experiment, my aim has been to keep things as simple as possible.

In terms of performance, Goose has shown to be quite capable. In my tests, a single node was able to achieve a network speed of up to 200Mbps. I should note that I haven't tested it with higher bandwidth networks, so it's possible that it could perform even better. So, it's safe to say that it can reach at least 200Mbps, potentially even higher. While this may not be record-breaking, it's good enough for my personal use case.

Regarding potential IP conflicts in a masqueraded IP network, that's a great point. Currently, users are responsible for setting up their networks to avoid these conflicts. If you have ideas about how this process could be made easier, I'd love to hear them.

I'm in total agreement with you that built-in DNS and DHCP would be beneficial features. I've seen other people bringing up this point, and it's definitely something I'm considering for future updates.

Thanks again for your insights!

**Comment by lonnietc** [comment]
Hello, my friend @nickjfree 

Hope that you are doing well.

For the project that I am working on now, it is to have a type of massively scalingP2P system that can function perhaps like Goose, but also like an encrypted overlay network such that the users can start it up and use it as a type of high-scaling P2P mesh network for specific applications that will be talking on "named" channels like you have now.

I would love to discuss the project goals more with you and maybe you could contact me so that we can see what we might be able to do on this.  I will look forward to hearing from you soon.

Have a great day.
