### ISSUE TITLE
P2P Relay Mesh Network?

### ISSUE THREAD

**Issue by lonnietc** [nickjfree/goose#7]
Hello,

Does Goose act as a P2P Relay Mesh network?

If you have "A" connected to "B" and "B" connected to "C" then can "A" message "C" passing messages through "B"?

```
A <=> B <=> C
```

Also, what type of scaling can Goose handle?
Thanks

**Comment by nickjfree** [comment]
Yes, Goose supports a P2P relay mesh network architecture with a maximum hop of 3. In your example of nodes A, B, and C, Goose enables messages from node A to be relayed through node B to reach node C, as long as the total hop count does not exceed 3 hops.
Goose has been successfully run with a network of 30+ nodes, and I believe it has the potential to scale even further. In fact, I'm confident that Goose can handle networks with hundreds of nodes without encountering significant scalability issues.
